var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];
export function generate() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
const messages = [
    "Hey, how's it going?",
    "What are you up to today?",
    "Did you hear about the new movie?",
    "I'm so tired, I need a nap.",
    "What's your favorite hobby?",
    "Have you tried that new restaurant downtown?",
    "I'm excited for the weekend!",
    "Do you have any plans for vacation?",
    "I can't believe it's already March!",
    "I'm craving pizza right now.",
    // Add more chat messages here...
    "This weather is perfect for a picnic!",
    "Do you prefer tea or coffee?",
    "I just finished reading a great book.",
    "Let's plan a hiking trip soon!",
    "What's your favorite music genre?",
    "I'm learning to play the guitar.",
    "Have you ever been to Europe?",
    "I'm thinking of redecorating my room.",
    "Let's go to the beach next weekend!",
    "Do you have any pets?",
    "I love watching documentaries.",
    "What's your dream travel destination?",
    "I'm trying to eat healthier.",
    "Let's meet up for lunch sometime!",
    "What's the best movie you've seen recently?",
    "I'm excited for the concert next week.",
    "What's the last thing you binge-watched?",
    "Let's try cooking a new recipe together!",
    "Have you ever been skydiving?",
    "I'm planning to start a new hobby.",
    "Do you enjoy going to museums?",
    "I'm thinking of getting a new phone.",
    "Let's go shopping this weekend!",
    "What's your favorite dessert?",
    "I'm feeling really productive today.",
    "Do you believe in aliens?",
    "I'm considering adopting a pet.",
    "Let's go for a bike ride!",
    "What's your favorite holiday?",
    "I'm looking forward to the new season of my favorite show.",
    "Do you prefer sweet or savory snacks?",
    "I just finished a challenging workout.",
    "Let's have a game night soon!",
    "What's the best book you've read recently?",
    "I'm thinking of learning a new language.",
    "Do you enjoy gardening?",
    "I'm planning a road trip for the summer.",
    "Let's go for a hike in the mountains!",
    "What's your favorite type of cuisine?",
    "I'm trying to be more eco-friendly.",
    "Do you enjoy going to concerts?",
    "I'm considering starting a blog.",
    "Let's have a picnic in the park!",
    "What's the most adventurous thing you've done?",
    "I'm excited for the upcoming festival.",
    "Do you like spicy food?",
    "I'm thinking of taking up painting.",
    "Let's have a movie marathon!",
    "What's your favorite board game?",
    "I'm planning to redecorate my garden.",
    "Do you enjoy going to art galleries?",
    "I'm looking forward to the holiday season.",
    "Let's have a barbecue this weekend!",
    "What's the best concert you've been to?",
    "I'm considering starting a new business.",
    "Do you like to go camping?",
    "I'm thinking of volunteering for a charity.",
    "Let's have a karaoke night!",
    "What's your favorite type of music?",
    "I'm excited for the summer vacation.",
    "Do you enjoy going to the theater?",
    "I'm planning to take up yoga.",
    "Let's have a beach bonfire!",
    "What's the most interesting place you've visited?",
    "I'm considering taking up photography.",
    "Do you like to go fishing?",
    "I'm thinking of adopting a plant-based diet.",
    "Let's have a picnic by the lake!",
    "What's your favorite outdoor activity?",
    "I'm excited for the upcoming art exhibition.",
    "Do you like to go skiing?",
    "I'm planning to learn how to cook Thai cuisine.",
    "Let's have a potluck dinner party!",
    "What's the best movie you've seen in theaters?",
    "I'm considering starting a book club.",
    "Do you like to go snorkeling?",
    "I'm thinking of organizing a charity fundraiser.",
    "Let's have a DIY craft night!",
    "What's your favorite childhood memory?",
    "I'm excited for the weekend getaway.",
    "Do you like to go horseback riding?",
    "I'm planning to take up meditation.",
    "Let's have a game of volleyball at the beach!",
    "What's the best adventure you've had?",
    "I'm considering starting a podcast.",
    "Do you like to go rock climbing?",
    "I'm thinking of hosting a themed party.",
    "Let's have a movie night under the stars!",
    "What's your favorite thing to do on a rainy day?",
    "I'm excited for the upcoming music festival.",
    "Do you like to go paddleboarding?",
    "I'm planning to learn how to dance salsa.",
    "Let's have a barbecue in the backyard!",
    "What's the best live performance you've seen?",
    "I'm considering starting a fitness challenge.",
    "Do you like to go kayaking?",
    "I'm thinking of organizing a community event.",
    "Let's have a bonfire at the beach!",
    "What's your favorite way to relax?",
    "I'm excited for the upcoming road trip.",
    "Do you like to go mountain biking?",
    "I'm planning to learn how to make sushi.",
    "Let's have a picnic in the countryside!",
    "What's the best festival you've attended?",
    "I'm considering starting a creative project.",
    "Do you like to go surfing?",
    "I'm thinking of hosting a cooking competition.",
    "Let's have a camping trip in the wilderness!",
    "What's your favorite way to spend a lazy day?",
    "I'm excited for the upcoming camping trip.",
    "Do you like to go zip-lining?",
    "I'm planning to learn how to make cocktails.",
    "Let's have a barbecue in the mountains!",
    "What's the best adventure sport you've tried?",
    "I'm considering starting a new hobby group.",
    "Do you like to go bungee jumping?",
    "I'm thinking of organizing a charity run.",
    "Let's have a beach party with live music!",
    "What's your favorite memory from a trip?",
    "I'm excited for the upcoming ski trip.",
    "Do you like to go scuba diving?",
    "I'm planning to learn how to bake pastries.",
    "Let's have a picnic in the forest!",
    "What's the best wildlife encounter you've had?",
    "I'm considering starting a gardening club.",
    "Do you like to go parasailing?",
    "I'm thinking of hosting a wine tasting event.",
    "Let's have a barbecue by the river!",
    "What's your favorite way to enjoy nature?",
    "I'm excited for the upcoming sailing trip.",
    "Do you like to go hot air ballooning?",
    "I'm planning to learn how to make chocolate.",
    "Let's have a picnic on a boat!",
    "What's the best outdoor adventure you've had?",
    "I'm considering starting a birdwatching group.",
    "Do you like to go hang gliding?",
    "I'm thinking of organizing a food festival.",
    "Let's have a barbecue on a rooftop!",
    "What's your favorite outdoor experience?",
    "I'm excited for the upcoming jungle trek.",
    "Do you like to go whitewater rafting?",
    "I'm planning to learn how to brew beer.",
    "Let's have a picnic in a vineyard!",
    "What's the best camping trip you've been on?",
    "I'm considering starting a hiking club.",
    "Do you like to go spelunking?",
    "I'm thinking of hosting a farmers' market.",
    "Let's have a barbecue at a waterfall!",
    "What's your favorite outdoor destination?",
    "I'm excited for the upcoming safari.",
    "Do you like to go wildlife spotting?",
    "I'm planning to learn how to make ice cream.",
    "Let's have a picnic in a canyon!",
    "What's the best adventure you've had in nature?",
    "I'm considering starting a conservation project.",
    "Do you like to go birdwatching?",
    "I'm thinking of organizing a tree planting event.",
    "Let's have a barbecue on an island!",
    "What's your favorite outdoor memory?",
    "I'm excited for the upcoming mountain climb.",
    "Do you like to go rock climbing?",
    "I'm planning to learn how to make cocktails.",
    "Let's have a picnic in the forest!",
    "What's the best adventure sport you've tried?",
    "I'm considering starting a new hobby group.",
    "Do you like to go bungee jumping?",
    "I'm thinking of organizing a charity run.",
    "Let's have a beach party with live music!",
    "What's your favorite memory from a trip?",
    "I'm excited for the upcoming ski trip.",
    "Do you like to go scuba diving?",
    "I'm planning to learn how to bake pastries.",
    "Let's have a picnic in the mountains!",
    "What's the best wildlife encounter you've had?",
    "I'm considering starting a gardening club.",
    "Do you like to go parasailing?",
    "I'm thinking of hosting a wine tasting event.",
    "Let's have a barbecue by the river!",
    "What's your favorite way to enjoy nature?",
    "I'm excited for the upcoming sailing trip.",
    "Do you like to go hot air ballooning?",
    "I'm planning to learn how to make chocolate.",
    "Let's have a picnic on a boat!",
    "What's the best outdoor adventure you've had?",
    "I'm considering starting a birdwatching group.",
    "Do you like to go hang gliding?",
    "I'm thinking of organizing a food festival.",
    "Let's have a barbecue on a rooftop!",
    "What's your favorite outdoor experience?",
    "I'm excited for the upcoming jungle trek.",
    "Do you like to go whitewater rafting?",
    "I'm planning to learn how to brew beer.",
    "Let's have a picnic in a vineyard!",
    "What's the best camping trip you've been on?",
    "I'm considering starting a hiking club.",
    "Do you like to go spelunking?",
    "I'm thinking of hosting a farmers' market.",
    "Let's have a barbecue at a waterfall!",
    "What's your favorite outdoor destination?",
    "I'm excited for the upcoming safari.",
    "Do you like to go wildlife spotting?",
    "I'm planning to learn how to make ice cream.",
    "Let's have a picnic in a canyon!",
    "What's the best adventure you've had in nature?",
    "I'm considering starting a conservation project.",
    "Do you like to go birdwatching?",
    "I'm thinking of organizing a tree planting event.",
    "Let's have a barbecue on an island!",
    "What's your favorite outdoor memory?",
    "I'm excited for the upcoming mountain climb."
  ];
  
  // Function to generate a random chat message
export function generateRandomMessage() {
    const randomIndex = Math.floor(Math.random() * messages.length);
    return messages[randomIndex];
  }

function isPrime(num) {
    if (num <= 1) {
      return false;
    }
    for (let i = 2; i <= Math.sqrt(num); i++) {
      if (num % i === 0) {
       return false;
      }
    }
    return true;
   }

  export function findNthPrime(n) {
    let count = 0;
    let num = 2;
    while (count < n) {
      if (isPrime(num)) {
       count++;
      }
      num++;
    }
    return num - 1;
   }
  

